FROM ubuntu

RUN apt update -yy && \
    apt install -y iputils-ping net-tools && \
    apt install git -yy && \
    apt install libpcap-dev -yy && \
    apt install golang -yy && \
    apt install gcc && apt install g++ && \
    git clone https://github.com/Liverpoolfan92/Diploma_project.git && \
    git clone https://github.com/Liverpoolfan92/go.pkt.git